# Generated by Django 5.1.1 on 2024-10-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
