# Generated by Django 5.1.1 on 2024-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
