# Generated by Django 5.1.1 on 2024-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produtos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(default='none', upload_to='fotos_produtos/%Y/%m/%d/'),
        ),
    ]
