# Generated by Django 5.1.1 on 2024-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos_produtos/%Y/%m/%d/'),
        ),
    ]
