# Generated by Django 5.1.1 on 2024-10-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='open_to_sell',
            field=models.BooleanField(default=False),
        ),
    ]
